version: '2'

services:
  pg_db:
    image: postgres
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: driver
      POSTGRES_DB: car_share
      POSTGRES_PASSWORD: Aria016rnhod4017
    ports:
      - 5432:5432
    expose:
      - '5432'